[package]
name = "lasertargets"
version = "0.1.0"
edition = "2024"


[profile.dev]
opt-level = 0
debug = 2 
debug-assertions = true # Enables additional runtime checks for safety
overflow-checks = true  # Enables integer overflow checks

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = { version = "0.16.1" }
log = "0.4"            # For logging (optional, but useful)
pretty_env_logger = "0.5.0"
